name: back_end_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  mailer: ^6.4.1
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
